name: Maven verify

on: [push, pull_request]

# clear all permissions for GITHUB_TOKEN
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 17
          java-distribution: temurin
          maven-version: 3.8.7

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          set-java-home: 'false'
          cache: 'maven'

      - name: Build with Maven
        run: mvn verify -e -B -V -Pnative
