name: Maven verify

on: [push, pull_request]

# clear all permissions for GITHUB_TOKEN
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 21
          java-distribution: temurin
          maven-version: 3.9.1

      - name: Build with Maven
        run: mvn verify -e -B -V -Pnative
